title: <p align="center"> Chitra Govindasamy </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chitra-psg/">LinkedIn</a> |
  <a href="https://github.com/chitra-psg">GitHub</a>

  <br>   
 Passionate data anlaytics professional specializing in data modelling, reporting and presenting insights through various technologies.
  <br>
  </p>



theme: jekyll-theme-minimal
